apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/wdm-project-template-default: "true"
        io.kompose.service: order-service
    spec:
      containers:
        - args:
            - java
            - -jar
            - /app.jar
          image: boomm61/wdm-order:test
          imagePullPolicy: IfNotPresent
          name: order-service
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: "http://gateway.default.svc.cluster.local:8000"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service.default.svc.cluster.local:5001"
            - name: STOCK_SERVICE_URL
              value: "http://stock-service.default.svc.cluster.local:5002"
            - name: DATABASE_URL
              value: "jdbc:postgresql://order-db.default.svc.cluster.local:5432/wdmorder"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASS
              value: "ABC"
          resources: {}
      restartPolicy: Always

status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: order-service
status:
  loadBalancer: {}
